# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [206]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task1</p>

In [3]:
s=5
print("s =",str(s))
v=np.array([5,-2,4])
print("v=\n",str(v.reshape(3,1)))
A=np.arange(1,10).reshape(3,3)
print("A=\n",str(A))
B=np.arange(1,7).reshape(2,3)
print("B=\n",str(B))
C=np.arange(1,7).reshape(2,3).T
print("C=\n",str(C))

s = 5
v=
 [[ 5]
 [-2]
 [ 4]]
A=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B=
 [[1 2 3]
 [4 5 6]]
C=
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
#type your code here:


s = 5
v=
 [[ 5]
 [-2]
 [ 4]]
A=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B=
 [[1 2 3]
 [4 5 6]]
C=
 [[1 4]
 [2 5]
 [3 6]]


b) Print the data type of $s, v,$ and $A$ using `type` command in python.

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task2</p>

In [6]:
print("type(s) = ",type(s))
print("type(v) = ",type(v))
print("type(A) = ",type(A))
print("type(B) = ",type(B))
print("type(C) = ",type(C))

type(s) =  <class 'int'>
type(v) =  <class 'numpy.ndarray'>
type(A) =  <class 'numpy.ndarray'>
type(B) =  <class 'numpy.ndarray'>
type(C) =  <class 'numpy.ndarray'>


In [ ]:
#type your code here:


type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(A) = <class 'numpy.ndarray'>



c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task3</p>

In [7]:
print("s.shape = ",np.array(s).shape)
print("v.shape = ",v.shape)
print("A.shape = ",A.shape)
print("B.shape = ",B.shape)
print("C.shape = ",C.shape)

s.shape =  ()
v.shape =  (3,)
A.shape =  (3, 3)
B.shape =  (2, 3)
C.shape =  (3, 2)


In [ ]:
#type your code here:


s.shape = ()

v.shape = (3, 1)

A.shape = (3, 3)

B.shape = (2, 3)

C.shape = (3, 2)



d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task4</p>

In [8]:
print("A[2, 1] = ",str(A[2,1]))
print("\n")
print("A = \n",str(A))

A[2, 1] =  8


A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#type your code here:


A[2, 1] =  8

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]



e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task5</p>

In [9]:
print("A[:, [1]] =\n",str(A[:,1:2]))
print("\n")
print("B[[1], :] =\n",str(B[1:2,:]))

A[:, [1]] =
 [[2]
 [5]
 [8]]


B[[1], :] =
 [[4 5 6]]


In [ ]:
#type your code here:


A[:, [1]] =
 [[ 2]
 [ 5]
 [10]]

B[[1], :] =
 [[4 5 6]]



f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task6</p>

In [10]:
print("np.eye(4) =\n",str(np.eye(4)))
print("\n")
print("np.zeros(3) =\n",str(np.zeros(3)))
print("\n")
print("np.zeros(3,1) =\n",str(np.zeros((3,1))))
print("\n")
print("np.zeros(3,5) =\n",str(np.zeros((3,5))))
print("\n")
print("np.ones(2,3) =\n",str(np.ones((2,3))))
print("\n")
print("np.diag([4,5,6,7]) =\n",str(np.diag([4,5,6,7])))

np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


np.zeros(3) =
 [0. 0. 0.]


np.zeros(3,1) =
 [[0.]
 [0.]
 [0.]]


np.zeros(3,5) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


np.ones(2,3) =
 [[1. 1. 1.]
 [1. 1. 1.]]


np.diag([4,5,6,7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


In [ ]:
#type your code here:


np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) =
 [0. 0. 0.]

np.zeros(3, 1) =
 [[0.]
 [0.]
 [0.]]

np.zeros(3, 5) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(2, 3) =
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4 5 6 7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task7</p>

In [11]:
v1 = np.array([1,2,7,4]).reshape(4,1)
v2 = np.array([4,3,6,8]).reshape(4,1)
print("v1 = \n",str(v1))
print("\n")
print("v2 = \n",str(v2))
print("\n")
print("v1 + v2 =\n",str(v1+v2))
print("\n")
print("v1 - v2 =\n",str(v1-v2))
print("\n")
print("3 * v1 =\n",str(3*v1))
print("\n")
print("v1 / 2 =\n",str(v1/2))

v1 = 
 [[1]
 [2]
 [7]
 [4]]


v2 = 
 [[4]
 [3]
 [6]
 [8]]


v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]


v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]


3 * v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]


v1 / 2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]


In [ ]:
#type your code here:


v1 =
 [[1]
 [2]
 [7]
 [4]]

v2 =
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]

3*v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]

v1/2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task8</p>

In [12]:
print("Using numpy.dot = \n",str(np.dot(v1.T,v2)))
print("\n")
print("Using numpy.matmul = \n",str(np.matmul(v1.T,v2)))
print("\n")
print("Using  @ = \n",str(v1.T @ v2))

Using numpy.dot = 
 [[84]]


Using numpy.matmul = 
 [[84]]


Using  @ = 
 [[84]]


In [ ]:
#type your code here:


Using numpy.dot =
 [[84]]

Using numpy.matmul =
 [[84]]

Using @ =
 [[84]]



c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task9</p>

In [13]:
print("length of v1 Using numpy.linalg.norm =\n",str((np.linalg.norm(v1))))
print("\n")
print("length of v2 Using numpy.linalg.norm =\n",str((np.linalg.norm(v2))))
print("\n")
print("length of v1 Using the dot product and numpy.sqrt =\n",str((np.sqrt(v1.T @ v1))))
print("\n")
print("length of v2 Using the dot product and numpy.sqrt =\n",str((np.sqrt(v2.T @ v2))))

length of v1 Using numpy.linalg.norm =
 8.366600265340756


length of v2 Using numpy.linalg.norm =
 11.180339887498949


length of v1 Using the dot product and numpy.sqrt =
 [[8.36660027]]


length of v2 Using the dot product and numpy.sqrt =
 [[11.18033989]]


In [ ]:
#type your code here:


length of v1 Using numpy.linalg.norm =
 8.366600265340756

length of v2 Using numpy.linalg.norm =
 11.180339887498949

length of v1 Using the dot product and numpy.sqrt =
 [[8.36660027]]

length of v2 Using the dot product and numpy.sqrt =
 [[11.18033989]]



d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task10</p>

In [14]:
u=np.array([[3],[2],[-1],[4]])
v=np.array([[1],[-1],[1],[0]])
#u=np.array([3,2,-1,4]).reshape(4,1)
#v=np.array([1,-1,1,0]).reshape(4,1)
print("u.T @ v = \n",str(u.T @ v))

u.T @ v = 
 [[0]]


In [ ]:
#type your code here:


u.T @ v =
 [[0]]



# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task11</p>

In [15]:
u=np.array([2,7,2]).reshape(3,1)
v=np.array([8,2,4]).reshape(3,1)
A=np.array([[7,3,5],[4,6,2]])
B=np.array([[0,6,4],[2,3,0]])
print("u = \n",str(u))
print("\n")
print("v = \n",str(v))
print("\n")
print("A = \n",str(A))
print("\n")
print("B = \n",str(B))

u = 
 [[2]
 [7]
 [2]]


v = 
 [[8]
 [2]
 [4]]


A = 
 [[7 3 5]
 [4 6 2]]


B = 
 [[0 6 4]
 [2 3 0]]


In [16]:
print("A+B= \n",str(A+B))
print("\n")
print("B+A= \n",str(B+A))
print("\n")
print("3A= \n",str(3*A))
print("\n")
print("6B= \n",str(6*B))
print("\n")
print("2(3B) =\n",str(2*(3*B)))
print("\n")
print("6A + 15B =\n",str((6*A) + (15*B)))
print("\n")
print("3(2A + 5B) =\n",str((3*((2*A)+(5*B)))))
print("\n")
print("(3A^T)^T =\n",str(((3*A).T).T))



A+B= 
 [[7 9 9]
 [6 9 2]]


B+A= 
 [[7 9 9]
 [6 9 2]]


3A= 
 [[21  9 15]
 [12 18  6]]


6B= 
 [[ 0 36 24]
 [12 18  0]]


2(3B) =
 [[ 0 36 24]
 [12 18  0]]


6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]


3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]


(3A^T)^T =
 [[21  9 15]
 [12 18  6]]


In [ ]:
#type your code here:


u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]


 (3A^T)^T = 
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task12</p>

In [17]:
print("AU + Av =\n",str(np.dot(A,u)+np.dot(A,v)))
print("\n")
print("A(u + v) =\n",str(A @ (u+v)))
print("\n")
print("(A + B)u =\n",str(np.matmul((A + B),u)))
print("\n")
print("Au + Bu =\n",str((A @ u) + (B @ u)))
print("\n")
print("A(3u) =\n",str(np.dot(A,(3*u))))
print("\n")
print("3A(u) =\n",str((3*A) @ u))

AU + Av =
 [[127]
 [106]]


A(u + v) =
 [[127]
 [106]]


(A + B)u =
 [[95]
 [79]]


Au + Bu =
 [[95]
 [79]]


A(3u) =
 [[135]
 [162]]


3A(u) =
 [[135]
 [162]]


In [ ]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries

In [158]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[7. 4. 7. 1.]
 [1. 8. 8. 4.]
 [1. 8. 1. 5.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix).

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [110]:
sym.Matrix(A)

Matrix([
[0.0, 5.0, 7.0, 6.0],
[1.0, 1.0, 1.0, 4.0],
[9.0, 9.0, 6.0, 1.0]])

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task13</p>

In [159]:
R=A.copy()
R[0,:]/=R[0][0]
print(R)




[[1.         0.57142857 1.         0.14285714]
 [1.         8.         8.         4.        ]
 [1.         8.         1.         5.        ]]


In [160]:
R[1,:]=R[0,:]*R[1][0]-R[1,:]
print(R)

[[ 1.          0.57142857  1.          0.14285714]
 [ 0.         -7.42857143 -7.         -3.85714286]
 [ 1.          8.          1.          5.        ]]


In [161]:
R[2,:]=R[0,:]*R[2][0]-R[2,:]
print(R)

[[ 1.          0.57142857  1.          0.14285714]
 [ 0.         -7.42857143 -7.         -3.85714286]
 [ 0.         -7.42857143  0.         -4.85714286]]


In [162]:
#type your code here:


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [163]:
R[1,:]/=R[1][1]
print(R)

[[ 1.          0.57142857  1.          0.14285714]
 [-0.          1.          0.94230769  0.51923077]
 [ 0.         -7.42857143  0.         -4.85714286]]


In [164]:
R[2,:]=R[2,:]-R[2,1]*R[1,:]
print(R)

[[ 1.          0.57142857  1.          0.14285714]
 [-0.          1.          0.94230769  0.51923077]
 [ 0.          0.          7.         -1.        ]]


In [165]:
R[0,:]-=R[0,1]*R[1,:]
print(R)

[[ 1.          0.          0.46153846 -0.15384615]
 [-0.          1.          0.94230769  0.51923077]
 [ 0.          0.          7.         -1.        ]]


In [ ]:
#type your code here:



 R = 
 [[ 1.          0.          0.5         0.125     ]
 [ 0.          1.         -0.16666667  1.04166667]
 [ 0.          0.          6.16666667 -1.04166667]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [166]:
R[2,:]/=R[2][2]
print(R)

[[ 1.          0.          0.46153846 -0.15384615]
 [-0.          1.          0.94230769  0.51923077]
 [ 0.          0.          1.         -0.14285714]]


In [167]:
R[0,:]-=R[0,:]*R[2,:]
print(R)


[[ 1.          0.          0.         -0.17582418]
 [-0.          1.          0.94230769  0.51923077]
 [ 0.          0.          1.         -0.14285714]]


In [168]:
R[1,:]-=R[1,:]*R[2,:]
print(R)

[[ 1.          0.          0.         -0.17582418]
 [ 0.          1.          0.          0.59340659]
 [ 0.          0.          1.         -0.14285714]]


In [ ]:
#type your code here:




 R = 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [169]:
M = sym.Matrix(A)
M_rref = M.rref()
R = np.array((M_rref[0])).astype(np.float64)

In [170]:
print(R)

[[ 1.          0.          0.         -0.08791209]
 [ 0.          1.          0.          0.65384615]
 [ 0.          0.          1.         -0.14285714]]


In [171]:
np.linalg.matrix_rank(R)

3

In [ ]:
#type your code here:

# Use sympy.rref() method



 rank = 
 3

 The Row echelon form of matrix M 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$.

2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

# <p style="padding:10px;background-color:cyan;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task14</p>

In [204]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i,j]+=A[i,k]*B[k,j]

    ########################################################
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################

    for j in range(p):
      for i in range(m):
        for k in range(n):
          C[i,j]+=A[i,k]*B[k,j]

    '''    for j in range(p):
        C[:,j]=np.dot(A,B[:,j])'''

    ########################################################
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        for j in range(n):
            for k in range(p):
                C[i,k]+=A[i,j]*B[j,k]

        '''    for i in range(m):
        C[i,:]=np.dot(A[i,:],B)'''

    ########################################################
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
      for j in range(p):
        C[i,j]=np.dot(A[i,:],B[:,j])

    ########################################################
    return C

In [ ]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################


    ########################################################
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################


    ########################################################
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################


    ########################################################
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################


    ########################################################
    return C

In [179]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [200]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[6313. 5006. 6051. ... 5440. 5441. 5599.]
 [6219. 5970. 6327. ... 6203. 5811. 5857.]
 [6698. 5832. 6723. ... 6300. 6199. 6501.]
 ...
 [6424. 5707. 6359. ... 6291. 5895. 6164.]
 [6209. 5441. 5973. ... 6107. 5641. 5870.]
 [6386. 5718. 6517. ... 6403. 6032. 5833.]]
CPU times: user 7.58 ms, sys: 1.98 ms, total: 9.56 ms
Wall time: 5.83 ms


In [ ]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 3.69 ms


In [201]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[6313. 5006. 6051. ... 5440. 5441. 5599.]
 [6219. 5970. 6327. ... 6203. 5811. 5857.]
 [6698. 5832. 6723. ... 6300. 6199. 6501.]
 ...
 [6424. 5707. 6359. ... 6291. 5895. 6164.]
 [6209. 5441. 5973. ... 6107. 5641. 5870.]
 [6386. 5718. 6517. ... 6403. 6032. 5833.]]
CPU times: user 21 s, sys: 26.1 ms, total: 21.1 s
Wall time: 21.2 s


In [ ]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 659 ms


In [194]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[6313. 5006. 6051. ... 5440. 5441. 5599.]
 [6219. 5970. 6327. ... 6203. 5811. 5857.]
 [6698. 5832. 6723. ... 6300. 6199. 6501.]
 ...
 [6424. 5707. 6359. ... 6291. 5895. 6164.]
 [6209. 5441. 5973. ... 6107. 5641. 5870.]
 [6386. 5718. 6517. ... 6403. 6032. 5833.]]
CPU times: user 19.6 s, sys: 35.4 ms, total: 19.6 s
Wall time: 19.8 s


In [ ]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 1.77 s


In [202]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[6313. 5006. 6051. ... 5440. 5441. 5599.]
 [6219. 5970. 6327. ... 6203. 5811. 5857.]
 [6698. 5832. 6723. ... 6300. 6199. 6501.]
 ...
 [6424. 5707. 6359. ... 6291. 5895. 6164.]
 [6209. 5441. 5973. ... 6107. 5641. 5870.]
 [6386. 5718. 6517. ... 6403. 6032. 5833.]]
CPU times: user 19.6 s, sys: 33.5 ms, total: 19.6 s
Wall time: 19.7 s


In [ ]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 1.91 s


In [205]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[6313. 5006. 6051. ... 5440. 5441. 5599.]
 [6219. 5970. 6327. ... 6203. 5811. 5857.]
 [6698. 5832. 6723. ... 6300. 6199. 6501.]
 ...
 [6424. 5707. 6359. ... 6291. 5895. 6164.]
 [6209. 5441. 5973. ... 6107. 5641. 5870.]
 [6386. 5718. 6517. ... 6403. 6032. 5833.]]
CPU times: user 172 ms, sys: 0 ns, total: 172 ms
Wall time: 171 ms


In [ ]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 80 ms
