# <p style="padding:10px;background-color:purple;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task1:Structure Array</p>

In [1]:
import numpy as np

In [3]:
dt=np.dtype([('name',(np.str_,10)),('height',np.float64),("class",np.int32)])
arrstd=np.array([('sara',154.5,5),('alaa',160.4,6),('sama',156.8,4)],dtype=dt)
print(arrstd)
sorted_arrstd=np.sort(arrstd,order='height')
print(sorted_arrstd)

[('sara', 154.5, 5) ('alaa', 160.4, 6) ('sama', 156.8, 4)]
[('sara', 154.5, 5) ('sama', 156.8, 4) ('alaa', 160.4, 6)]


# <p style="padding:10px;background-color:purple;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task2:Solve Equations</p>

In [4]:
coffarr=np.array([[1,2,-3,2],
                 [2,-5,4,9],
                [-5,40,-1,-20],
                [5,-4,-1,60] ])
y=np.array([[30],[4],[-6],[5]])
res=np.linalg.solve(coffarr,y)
print(res)

[[19.46701571]
 [ 1.44371728]
 [-3.54973822]
 [-1.50183246]]


In [5]:
from scipy import linalg
coffarr=np.array([[1,2,-3,2],
                 [2,-5,4,9],
                [-5,40,-1,-20],
                [5,-4,-1,60] ])
y=np.array([[30],[4],[-6],[5]])
res=linalg.solve(coffarr,y)
print(res)

[[19.46701571]
 [ 1.44371728]
 [-3.54973822]
 [-1.50183246]]


# <p style="padding:10px;background-color:purple;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task3: Loss Function(L1)</p>

In [ ]:
def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
   
    #loss=abs(y-yhat).sum()
    loss=np.sum(np.abs(y-yhat))
   
    
    return loss

In [9]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y    = np.array([1 ,  0 ,  0 ,  1, 1])

l1_loss = L1(yhat,y)
print("L1 = " + str(l1_loss))


L1 = 1.1


# <p style="padding:10px;background-color:purple;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task3: Loss Function(L2)</p>

In [29]:
def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    
    #loss = sum((y-yhat)**2)
    loss=np.sum((np.dot(y,y)-(2*np.dot(y,yhat))+np.dot(yhat,yhat)))
  
    
    return loss

In [30]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y    = np.array([1 ,  0 ,  0 ,  1, 1])

l2_loss = L2(yhat,y)

print("L2 = " + str(l2_loss))

L2 = 0.4299999999999997


# <p style="padding:10px;background-color:purple;margin:0;color:gray;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Task4: dot product</p>

In [2]:
import numpy as np
x=np.random.rand(1000_000)
y=np.random.rand(1000_000)

In [5]:
x

array([0.18637732, 0.75015424, 0.51504758, ..., 0.95652105, 0.62081302,
       0.09513849])

In [6]:
y

array([0.80213826, 0.34422605, 0.61368067, ..., 0.92734473, 0.15966913,
       0.29095039])

In [6]:
import time

In [12]:
tic=time.time()
print(np.dot(x,y))
toc=time.time()
print(toc-tic)

tic=time.time()
res=0
for i in range(len(x)):
    res+=(x[i]*y[i])
print(res)
toc=time.time()
print(toc-tic)

tic=time.time()
print(sum(x*y))#this parallel for one dimension array only
toc=time.time()
print(toc-tic)


250202.82153544485
0.001992464065551758
250202.82153544365
0.7968993186950684
250202.82153544365
0.24981212615966797


In [13]:
tic=time.time()
res=0
for i in range(len(x)):
    res+=(x[i]*y[i])
print(res)
toc=time.time()
print(toc-tic)

250202.82153544365
0.7734224796295166


In [14]:
tic=time.time()
print(sum(x*y))#this parallel for one dimension array only
toc=time.time()
print(toc-tic)


250202.82153544365
0.21018218994140625


  I search about dot product parallism found two modules multiprocessing and threadpoolEccuter but multiprocessing gave me runtime error 

In [3]:
import numpy as np
from concurrent.futures import ThreadPoolExecutor
def dot_product_parallel(x, y,threads=4):
    size=len(x)//threads
    vectors=[]
    with ThreadPoolExecutor(max_workers=threads) as executor:
        for i in range(threads):
            start =i*size
            if i !=threads-1:
                end =(i+1)*size
            else:
               len(x)  
            vectors.append(executor.submit(np.dot, x[start:end], y[start:end]))
            dot_product=0
            for f in vectors:
                #print(f.result())
                dot_product+=f.result()
    return dot_product
import time

tic = time.time()
res = dot_product_parallel(x, y,threads=8)
toc = time.time()

print(res)
print(toc-tic)

218688.6677119655
0.004251956939697266
