# Lab 5: PCA Using Eigenvectors and Singular Value Decomposition

# First: you should run this cell

In [1]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

# Question 1 : PCA Using Eigenvectors

#### Create a matrix contains the following data

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **Sample #1** | 1 | 2 | 3 | 4 |
| **Sample #2** | 5 | 5 | 6 | 7 |
| **Sample #3**| 1 | 4 | 2 | 3 |
| **Sample #4**| 5 | 3 | 2 | 1 |
| **Sample #5**| 8 | 1 | 2 | 2 |

In [3]:
M = np.array([[1,2,3,4],
              [5,5,6,7],
              [1,4,2,3],
              [5,3,2,1],
              [8,1,2,2]])
print('M = \n{}\n'.format(M))

M = 
[[1 2 3 4]
 [5 5 6 7]
 [1 4 2 3]
 [5 3 2 1]
 [8 1 2 2]]



### Step 1: Standardize the dataset.
- Calculate data mean for each feature.
- Calculate data standard deviation for each feature.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **$\mu$** | 4 | 3 | 3 | 3.4 |
| **$\sigma$**| 3 | 1.58114 | 1.73205 | 2.30217 |


- Standardize the data.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **Sample #1** | -1.         | -0.63245553 |  0.         |  0.26062335 |
| **Sample #2** |  0.33333333 | 1.26491106 |  1.73205081 |  1.56374007 |
| **Sample #3** | -1.         | 0.63245553 | -0.57735027 | -0.1737489  |
| **Sample #4** |  0.33333333 | 0.         | -0.57735027 | -1.04249338 |
| **Sample #5** |  1.33333333 | -1.26491106 | -0.57735027 | -0.60812114 |




array([[-1.11803399, -0.70710678,  0.        ,  0.29138576],
       [ 0.372678  ,  1.41421356,  1.93649167,  1.74831455],
       [-1.11803399,  0.70710678, -0.64549722, -0.19425717],
       [ 0.372678  ,  0.        , -0.64549722, -1.16554303],
       [ 1.49071198, -1.41421356, -0.64549722, -0.6799001 ]])

In [13]:
print(" M =\n", M)
print("--------------------------------")
print("Data Mean =\n",np.mean(M,axis=0))
print("--------------------------------")
print("Data standard deviation =\n",np.std(M,axis=0))
X=(M-np.mean(M,axis=0))/np.std(M,axis=0)
print("--------------------------------")
print("X = \n",X)

 M =
 [[1 2 3 4]
 [5 5 6 7]
 [1 4 2 3]
 [5 3 2 1]
 [8 1 2 2]]
--------------------------------
Data Mean =
 [4.  3.  3.  3.4]
--------------------------------
Data standard deviation =
 [2.68328157 1.41421356 1.54919334 2.05912603]
--------------------------------
X = 
 [[-1.11803399 -0.70710678  0.          0.29138576]
 [ 0.372678    1.41421356  1.93649167  1.74831455]
 [-1.11803399  0.70710678 -0.64549722 -0.19425717]
 [ 0.372678    0.         -0.64549722 -1.16554303]
 [ 1.49071198 -1.41421356 -0.64549722 -0.6799001 ]]


In [3]:
#type your code here:


M = 
 [[1 2 3 4]
 [5 5 6 7]
 [1 4 2 3]
 [5 3 2 1]
 [8 1 2 2]]
---------------------------------------------
Data mean = 
 [[4.  3.  3.  3.4]]
---------------------------------------------
Data standard deviation = 
 [[3.         1.58113883 1.73205081 2.30217289]]
---------------------------------------------
X = 
 [[-1.         -0.63245553  0.          0.26062335]
 [ 0.33333333  1.26491106  1.73205081  1.56374007]
 [-1.          0.63245553 -0.57735027 -0.1737489 ]
 [ 0.33333333  0.         -0.57735027 -1.04249338]
 [ 1.33333333 -1.26491106 -0.57735027 -0.60812114]]


### Step 2: Calculate the covariance matrix for the features in the dataset.

-  Calculate covariance matrix using the formula: $C = \frac{X^TX}{n-1}$,  where $n$ is the number of data points.
##### Note: This formula is used because the data has <b>zero</b> mean and <b>1</b> standard deviation.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
|**Feature #1** |  1.         | -0.31622777 |  0.04811252 | -0.18098843 |
|**Feature #2** | -0.31622777 |  1.         |  0.63900965 |  0.61812254 |
|**Feature #3** |  0.04811252 |  0.63900965 |  1.         |  0.94044349 |
|**Feature #4** | -0.18098843 |  0.61812254 |  0.94044349 |  1.         |

In [14]:
C=(X.T @ X)/(M.shape[1]-1)
print("C =",C)

C = [[ 1.66666667 -0.52704628  0.08018754 -0.30164739]
 [-0.52704628  1.66666667  1.06501608  1.03020423]
 [ 0.08018754  1.06501608  1.66666667  1.56740582]
 [-0.30164739  1.03020423  1.56740582  1.66666667]]


In [4]:
#type your code here:


C = 
[[ 1.         -0.31622777  0.04811252 -0.18098843]
 [-0.31622777  1.          0.63900965  0.61812254]
 [ 0.04811252  0.63900965  1.          0.94044349]
 [-0.18098843  0.61812254  0.94044349  1.        ]]



### Step 3: Calculate the eigenvalues and eigenvectors for the covariance matrix and sort eigenvalues and their corresponding eigenvectors.

- Find eigen values and the corresponding eigen vectors for the covariance matrix
- Calculate how much variance captured in each component. $\frac{\lambda_j}{\sum_{k=1}^{m}\lambda_k}$, where $m$ is the number of features.

| Eigenvector #1 | Eigenvector #2 | Eigenvector #3 | Eigenvector #4 |
| --- | --- | --- | --- |
| 0.16195986 | -0.91705888 | -0.30707099 |  0.19616173 |
|-0.52404813 |  0.20692161 | -0.81731886 |  0.12061043 |
|-0.58589647 | -0.3205394  |  0.1882497  | -0.72009851 |
|-0.59654663 | -0.11593512 |  0.44973251 |  0.65454704 |

In [19]:
Eignvalues,Eignvectors=np.linalg.eig(C)
print("Eignvalues =\n",Eignvalues)
print("-"*50)
print("Percentage of variance =\n",100*(Eignvalues/sum(Eignvalues)))
print("-"*50)
print("Eigenvectors =\n",Eignvectors)


Eignvalues =
 [4.19298873 1.77548084 0.65647841 0.04171869]
--------------------------------------------------
Percentage of variance =
 [62.89483102 26.63221259  9.8471761   0.6257803 ]
--------------------------------------------------
Eigenvectors =
 [[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]


In [5]:
#type your code here:


Eigenvalues = 
[2.51579324 1.0652885  0.39388704 0.02503121]
---------------------------------------------
Percentage of variance = 
 [0.62894831 0.26632213 0.09847176 0.0062578 ]
---------------------------------------------
Eigenvectors = 
[[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]


### Step 4: Pick $k$ eigenvalues and form a matrix of eigenvectors.

- Select the first two eigen vectors

In [20]:
k=2
eig_vecs_2=Eignvectors[:,:k]
print("eig_vecs_2 =\n",eig_vecs_2)


eig_vecs_2 =
 [[ 0.16195986 -0.91705888]
 [-0.52404813  0.20692161]
 [-0.58589647 -0.3205394 ]
 [-0.59654663 -0.11593512]]


In [6]:
#type your code here:


eig_vecs_2 = 
 [[ 0.16195986 -0.91705888]
 [-0.52404813  0.20692161]
 [-0.58589647 -0.3205394 ]
 [-0.59654663 -0.11593512]]


### Step 5:Transform the standardized matrix matrix.

- `M_transformed = X @ eig_vecs_2`

In [43]:
np.set_printoptions(suppress=True)
M_transformed = X @ eig_vecs_2
print("M_transformed =\n",M_transformed )

M_transformed =
 [[ 0.01565617  0.84520548]
 [-2.8582919  -0.87254925]
 [-0.0575566   1.40104719]
 [ 1.13385419  0.000267  ]
 [ 1.76633814 -1.37397042]]


In [7]:
#type your code here:


M_transformed = 
 [[ 0.01400331  0.75597476]
 [-2.55653399 -0.78043177]
 [-0.05148019  1.2531347 ]
 [ 1.01415002  0.00023881]
 [ 1.57986086 -1.2289165 ]]


# Question 2 : Singular Value Decomposition (SVD)

#### For a square (real) matrices of size $(n,n)$ can be "eigendecomposed"  :
$$A = V . Diag(\Lambda). V^T$$

With $V$: eigenvectors 
; $Diag(\Lambda)$: eigenvalues (on the diagonal).

#### But for a non square  of size $(n,m) (n \neq m)$, we need to use the  Singular Value Decomposition (SVD)

- Let $A $ be a matrix of size $(n,m)$ with  $n \neq m$ the SVD of A is defined by:

$$A= U . S . V^T $$

Where:
 $U$: size $(n,n)$, square;
 $V$: size $(m,m)$, square;
 $S$: size $(n,m)$, rectanguler if $n \neq m$
 
- The values on the "diagonal" of $S$ are called: **singular values**. The singular values are generally sorted by decreasing order.
- The columns of $U$ are called the **left-singular vectors**
- The columns of $V$ are called the **right-singular vectors**

#### (a) For the matrix $A$, find the SVD

In [23]:
A = np.array([[1, 1, 1],
              [3, 4, 5],
              [4, 4, 4],                            
              [4, 5, 4]                      
              ])
rank = np.linalg.matrix_rank(A)
n, m = A.shape
print("n = ", n)
print("---------------------------------------------")
print("m = ", m)
print("---------------------------------------------")
print("rank = ", rank)
print("---------------------------------------------")
print("A = \n", A)

n =  4
---------------------------------------------
m =  3
---------------------------------------------
rank =  3
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]


- `U, s, VT = np.linalg.svd(A, full_matrices=True)`

In [34]:
U, s, VT = np.linalg.svd(A, full_matrices=False)

In [35]:
print("U = \n",U)
print("\n",U.shape)
print("-"*50)
print("s = \n",s)
print("\n",s.shape)
print("-"*50)
print("VT = \n",VT)
print("\n",VT.shape)

U = 
 [[-0.13820166  0.06547495 -0.18824681]
 [-0.55997677 -0.81882357  0.1263091 ]
 [-0.55280665  0.26189981 -0.75298723]
 [-0.60144088  0.50660585  0.61775349]]

 (4, 3)
--------------------------------------------------
s = 
 [12.49789499  1.23098537  0.53599988]

 (3,)
--------------------------------------------------
VT = 
 [[-0.51489647 -0.60782554 -0.60450785]
 [ 0.55486191  0.30122956 -0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]

 (3, 3)


In [9]:
#type your code here:


U:
 [[-0.13820166 -0.06547495 -0.18824681 -0.9701425 ]
 [-0.55997677  0.81882357  0.1263091  -0.        ]
 [-0.55280665 -0.26189981 -0.75298723  0.24253563]
 [-0.60144088 -0.50660585  0.61775349 -0.        ]]
---------------------------------------------
s:
 [12.49789499  1.23098537  0.53599988]
---------------------------------------------
VT:
 [[-0.51489647 -0.60782554 -0.60450785]
 [-0.55486191 -0.30122956  0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]


- Construct the matrix $A$ from the SVD:
$$A= U . S . V^T $$
Where:
 $U$: size $(n,n)$, square;
 $V$: size $(m,m)$, square;
 $S$: size $(n,m)$, rectanguler if $n \neq m$

In [36]:
print("U = \n",U)

print("-"*50)
S=np.diag(s)
print("S = \n",S)

print("-"*50)
print("VT = \n",VT)

print("-"*50)
print("A = \n",A)

print("-"*50)
print("U @ S @ VT\n",U @ S @ VT)


U = 
 [[-0.13820166  0.06547495 -0.18824681]
 [-0.55997677 -0.81882357  0.1263091 ]
 [-0.55280665  0.26189981 -0.75298723]
 [-0.60144088  0.50660585  0.61775349]]
--------------------------------------------------
S = 
 [[12.49789499  0.          0.        ]
 [ 0.          1.23098537  0.        ]
 [ 0.          0.          0.53599988]]
--------------------------------------------------
VT = 
 [[-0.51489647 -0.60782554 -0.60450785]
 [ 0.55486191  0.30122956 -0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]
--------------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
--------------------------------------------------
U @ S @ VT
 [[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]


In [10]:
#type your code here:


U=
 [[-0.13820166 -0.06547495 -0.18824681 -0.9701425 ]
 [-0.55997677  0.81882357  0.1263091  -0.        ]
 [-0.55280665 -0.26189981 -0.75298723  0.24253563]
 [-0.60144088 -0.50660585  0.61775349 -0.        ]]
---------------------------------------------
S=
 [[12.49789499  0.          0.        ]
 [ 0.          1.23098537  0.        ]
 [ 0.          0.          0.53599988]
 [ 0.          0.          0.        ]]
---------------------------------------------
VT=
 [[-0.51489647 -0.60782554 -0.60450785]
 [-0.55486191 -0.30122956  0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
U @ S @ VT=
 [[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]


#### $k$-rank approximation

- Construct the matrix $\tilde{A}$ using **$k$-rank approximation**.
- Calculate the approximation error using frobenius norm.

$$\tilde{A}= \tilde{U} . \tilde{S} . \tilde{V}^T $$
Where:
 $\tilde{U}$: size $(n,k)$,
  $\tilde{S}$: size $(k,k)$,
 $\tilde{V}$: size $(k,m)$;


In [37]:
print("-"*50)
k=3
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))


--------------------------------------------------
k = 
 3
--------------------------------------------------
A =
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
--------------------------------------------------
A_tilde =
 [[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]
--------------------------------------------------
A_tilde rank = 
 3
--------------------------------------------------
error = 
 7.373586149359714e-15


In [11]:
#type your code here:


---------------------------------------------
k =
 3
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
A_tilde = 
 [[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]
---------------------------------------------
A_tilde_rank = 
 3
---------------------------------------------
error = 
 8.350323853034144e-15


In [38]:
print("-"*50)
k=2
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))

--------------------------------------------------
k = 
 2
--------------------------------------------------
A =
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
--------------------------------------------------
A_tilde =
 [[0.93406572 1.07413313 0.98162029]
 [3.04424033 3.95025845 5.01233235]
 [3.73626287 4.29653251 3.92648116]
 [4.21637091 4.75672364 4.06031513]]
--------------------------------------------------
A_tilde rank = 
 2
--------------------------------------------------
error = 
 0.5359998808909961


In [12]:
#type your code here:


---------------------------------------------
k =
 2
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
A_tilde = 
 [[0.93406572 1.07413313 0.98162029]
 [3.04424033 3.95025845 5.01233235]
 [3.73626287 4.29653251 3.92648116]
 [4.21637091 4.75672364 4.06031513]]
---------------------------------------------
A_tilde_rank = 
 2
---------------------------------------------
error = 
 0.535999880890996


In [39]:
print("-"*50)
k=1
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))

--------------------------------------------------
k = 
 1
--------------------------------------------------
A =
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
--------------------------------------------------
A_tilde =
 [[0.88934457 1.04985441 1.044124  ]
 [3.60351884 4.25388574 4.2306668 ]
 [3.55737826 4.19941766 4.17649602]
 [3.87034549 4.56886954 4.54393133]]
--------------------------------------------------
A_tilde rank = 
 1
--------------------------------------------------
error = 
 1.3426171667971223


In [13]:
#type your code here:


---------------------------------------------
k =
 1
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
A_tilde = 
 [[0.88934457 1.04985441 1.044124  ]
 [3.60351884 4.25388574 4.2306668 ]
 [3.55737826 4.19941766 4.17649602]
 [3.87034549 4.56886954 4.54393133]]
---------------------------------------------
A_tilde_rank = 
 1
---------------------------------------------
error = 
 1.3426171667971218


#### (b) Repeat the previous steps in (a) for the following matrix

In [40]:
A = np.array([[1, 1, 1, 0, 1],
              [3, 4, 5, 1, 0],
              [4, 4, 4, 0, 1],                            
              [4, 5, 4, 1, 1],                            
              [4, 6, 4, 0, 1],                            
              [4, 7, 4, 1, 1],                            
              [4, 8, 4, 0, 1],                            
              [4, 9, 4, 1, 0],                            
              ])

n, m=A.shape
print("n= ", n)
print("---------------------------------------------")
print("m = ", m)
print("---------------------------------------------")
print("rank = ", rank)
print("---------------------------------------------")
print("A = \n", A)

n=  8
---------------------------------------------
m =  5
---------------------------------------------
rank =  3
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]


In [41]:
U, s, VT = np.linalg.svd(A, full_matrices=False)
print("U = \n",U)
print("\n",U.shape)
print("-"*50)
print("s = \n",s)
print("\n",s.shape)
print("-"*50)
print("VT = \n",VT)
print("\n",VT.shape)


U = 
 [[-0.07796472  0.1530172   0.35302976 -0.22877679  0.57696258]
 [-0.30094927  0.52061094 -0.6793994   0.25175352  0.33679431]
 [-0.3005767   0.46361787  0.32739721  0.22028811 -0.48946108]
 [-0.33654592  0.28310997  0.04237127 -0.58222388 -0.21766838]
 [-0.36661023  0.07504788  0.30162828  0.30797535 -0.06535036]
 [-0.40257945 -0.10546002  0.01660234 -0.49453663  0.20644234]
 [-0.43264377 -0.31352211  0.27585935  0.3956626   0.35876036]
 [-0.46485226 -0.54351365 -0.37074053 -0.0283843  -0.30188407]]

 (8, 5)
--------------------------------------------------
s = 
 [22.57699942  3.35144935  1.90842851  1.00414786  0.62966044]

 (5,)
--------------------------------------------------
VT = 
 [[-0.45161209 -0.74541953 -0.4782719  -0.06665752 -0.08490591]
 [ 0.34372285 -0.65113632  0.65440094  0.04617323  0.16584191]
 [ 0.36014096 -0.02458908 -0.35185784 -0.51936256  0.69003801]
 [-0.19757174  0.04402548  0.30385545 -0.84986617 -0.38003491]
 [-0.713558    0.13352287  0.35620687  0.037

In [15]:
#type your code here:


U:
 [[-0.07796472  0.1530172  -0.35302976  0.22877679 -0.57696258 -0.38937491
  -0.44740288  0.3299552 ]
 [-0.30094927  0.52061094  0.6793994  -0.25175352 -0.33679431 -0.
  -0.          0.        ]
 [-0.3005767   0.46361787 -0.32739721 -0.22028811  0.48946108  0.15935356
  -0.02773061  0.52274434]
 [-0.33654592  0.28310997 -0.04237127  0.58222388  0.21766838 -0.4401089
   0.38618031 -0.2749455 ]
 [-0.36661023  0.07504788 -0.30162828 -0.30797535  0.06535036  0.02405806
  -0.44256981 -0.68805437]
 [-0.40257945 -0.10546002 -0.01660234  0.49453663 -0.20644234  0.73214008
  -0.05062814  0.0274791 ]
 [-0.43264377 -0.31352211 -0.27585935 -0.3956626  -0.35876036 -0.08606789
   0.58215114  0.08282124]
 [-0.46485226 -0.54351365  0.37074053  0.0283843   0.30188407 -0.29203118
  -0.33555216  0.2474664 ]]
---------------------------------------------
s:
 [22.57699942  3.35144935  1.90842851  1.00414786  0.62966044]
---------------------------------------------
VT:
 [[-0.45161209 -0.74541953 -0.4782

In [44]:
print("U = \n",U)
#print("\n",U.shape)
print("-"*50)
S=np.diag(s)
print("s = \n",S)
#print("\n",s.shape)
print("-"*50)
print("VT = \n",VT)
#print("\n",VT.shape)
print("-"*50)
print("A = \n",A)

print("-"*50)
print("U @ S @VT = \n",U @ S @ VT)

U = 
 [[-0.07796472  0.1530172   0.35302976 -0.22877679  0.57696258]
 [-0.30094927  0.52061094 -0.6793994   0.25175352  0.33679431]
 [-0.3005767   0.46361787  0.32739721  0.22028811 -0.48946108]
 [-0.33654592  0.28310997  0.04237127 -0.58222388 -0.21766838]
 [-0.36661023  0.07504788  0.30162828  0.30797535 -0.06535036]
 [-0.40257945 -0.10546002  0.01660234 -0.49453663  0.20644234]
 [-0.43264377 -0.31352211  0.27585935  0.3956626   0.35876036]
 [-0.46485226 -0.54351365 -0.37074053 -0.0283843  -0.30188407]]
--------------------------------------------------
s = 
 [[22.57699942  0.          0.          0.          0.        ]
 [ 0.          3.35144935  0.          0.          0.        ]
 [ 0.          0.          1.90842851  0.          0.        ]
 [ 0.          0.          0.          1.00414786  0.        ]
 [ 0.          0.          0.          0.          0.62966044]]
--------------------------------------------------
VT = 
 [[-0.45161209 -0.74541953 -0.4782719  -0.06665752 -0.08490

In [16]:
#type your code here:


U=
 [[-0.07796472  0.1530172  -0.35302976  0.22877679 -0.57696258 -0.38937491
  -0.44740288  0.3299552 ]
 [-0.30094927  0.52061094  0.6793994  -0.25175352 -0.33679431 -0.
  -0.          0.        ]
 [-0.3005767   0.46361787 -0.32739721 -0.22028811  0.48946108  0.15935356
  -0.02773061  0.52274434]
 [-0.33654592  0.28310997 -0.04237127  0.58222388  0.21766838 -0.4401089
   0.38618031 -0.2749455 ]
 [-0.36661023  0.07504788 -0.30162828 -0.30797535  0.06535036  0.02405806
  -0.44256981 -0.68805437]
 [-0.40257945 -0.10546002 -0.01660234  0.49453663 -0.20644234  0.73214008
  -0.05062814  0.0274791 ]
 [-0.43264377 -0.31352211 -0.27585935 -0.3956626  -0.35876036 -0.08606789
   0.58215114  0.08282124]
 [-0.46485226 -0.54351365  0.37074053  0.0283843   0.30188407 -0.29203118
  -0.33555216  0.2474664 ]]
---------------------------------------------
S=
 [[22.57699942  0.          0.          0.          0.        ]
 [ 0.          3.35144935  0.          0.          0.        ]
 [ 0.          0.   

In [45]:
print("-"*50)
k=5
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))

--------------------------------------------------
k = 
 5
--------------------------------------------------
A =
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
--------------------------------------------------
A_tilde =
 [[ 1.  1.  1.  0.  1.]
 [ 3.  4.  5.  1. -0.]
 [ 4.  4.  4. -0.  1.]
 [ 4.  5.  4.  1.  1.]
 [ 4.  6.  4. -0.  1.]
 [ 4.  7.  4.  1.  1.]
 [ 4.  8.  4. -0.  1.]
 [ 4.  9.  4.  1. -0.]]
--------------------------------------------------
A_tilde rank = 
 5
--------------------------------------------------
error = 
 2.6168750065883512e-14


In [17]:
#type your code here:


---------------------------------------------
k =
 5
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
---------------------------------------------
A_tilde = 
 [[ 1.  1.  1. -0.  1.]
 [ 3.  4.  5.  1.  0.]
 [ 4.  4.  4. -0.  1.]
 [ 4.  5.  4.  1.  1.]
 [ 4.  6.  4. -0.  1.]
 [ 4.  7.  4.  1.  1.]
 [ 4.  8.  4. -0.  1.]
 [ 4.  9.  4.  1.  0.]]
---------------------------------------------
A_tilde_rank = 
 5
---------------------------------------------
error = 
 1.2015232257456147e-14


In [46]:
print("-"*50)
k=4
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))

--------------------------------------------------
k = 
 4
--------------------------------------------------
A =
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
--------------------------------------------------
A_tilde =
 [[ 1.25922885  0.95149241  0.87059342 -0.0136649   0.78670532]
 [ 3.15132143  3.97168433  4.92446062  0.9920233  -0.12450796]
 [ 3.78008551  4.04115099  4.10978092  0.01159249  1.18094665]
 [ 3.90220176  5.01830027  4.0488207   1.0051553   1.08046884]
 [ 3.97063813  6.00549427  4.01465739  0.00154777  1.02415908]
 [ 4.09275439  6.98264355  3.95369718  0.99511058  0.92368127]
 [ 4.16119076  7.96983756  3.91953386 -0.00849695  0.86737151]
 [ 3.86436371  9.02538062  4.06770939  1.00714988  0.11160215]]
--------------------------------------------------
A_tilde rank = 
 4
--------------------------------------------------
error = 
 0.6296604396728644


In [18]:
#type your code here:


---------------------------------------------
k =
 4
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
---------------------------------------------
A_tilde = 
 [[ 1.25922885  0.95149241  0.87059342 -0.0136649   0.78670532]
 [ 3.15132143  3.97168433  4.92446062  0.9920233  -0.12450796]
 [ 3.78008551  4.04115099  4.10978092  0.01159249  1.18094665]
 [ 3.90220176  5.01830027  4.0488207   1.0051553   1.08046884]
 [ 3.97063813  6.00549427  4.01465739  0.00154777  1.02415908]
 [ 4.09275439  6.98264355  3.95369718  0.99511058  0.92368127]
 [ 4.16119076  7.96983756  3.91953386 -0.00849695  0.86737151]
 [ 3.86436371  9.02538062  4.06770939  1.00714988  0.11160215]]
---------------------------------------------
A_tilde_rank = 
 4
---------------------------------------------
error = 
 0.6296604396728651


In [47]:
print("-"*50)
k=3
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))

--------------------------------------------------
k = 
 3
--------------------------------------------------
A =
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
--------------------------------------------------
A_tilde =
 [[ 1.21384154  0.96160619  0.94039684 -0.20890102  0.69940153]
 [ 3.20126712  3.96055479  4.84764664  1.20686756 -0.02843599]
 [ 3.82378874  4.03141247  4.04256754  0.19958445  1.26501107]
 [ 3.78669365  5.04403927  4.2264664   0.50829052  0.85828566]
 [ 4.03173774  5.99187927  3.92068925  0.26437126  1.14168593]
 [ 3.99464265  7.00450607  4.10458811  0.57307732  0.73496053]
 [ 4.23968675  7.95234607  3.79881096  0.32915806  1.0183608 ]
 [ 3.85873252  9.02663544  4.07636989  0.98292697  0.10077039]]
--------------------------------------------------
A_tilde rank = 
 3
--------------------------------------------------
error = 
 1.1852363429368313


In [19]:
#type your code here:


---------------------------------------------
k =
 3
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
---------------------------------------------
A_tilde = 
 [[ 1.21384154  0.96160619  0.94039684 -0.20890102  0.69940153]
 [ 3.20126712  3.96055479  4.84764664  1.20686756 -0.02843599]
 [ 3.82378874  4.03141247  4.04256754  0.19958445  1.26501107]
 [ 3.78669365  5.04403927  4.2264664   0.50829052  0.85828566]
 [ 4.03173774  5.99187927  3.92068925  0.26437126  1.14168593]
 [ 3.99464265  7.00450607  4.10458811  0.57307732  0.73496053]
 [ 4.23968675  7.95234607  3.79881096  0.32915806  1.0183608 ]
 [ 3.85873252  9.02663544  4.07636989  0.98292697  0.10077039]]
---------------------------------------------
A_tilde_rank = 
 3
---------------------------------------------
error = 
 1.1852363429368313


In [48]:
print("-"*50)
k=2
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))

--------------------------------------------------
k = 
 2
--------------------------------------------------
A =
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
--------------------------------------------------
A_tilde =
 [[0.97120303 0.97817264 1.17745474 0.14101019 0.2345008 ]
 [3.66822055 3.92867295 4.39143298 0.53346975 0.86625708]
 [3.59876756 4.04677607 4.2624133  0.52408954 0.83386553]
 [3.75757173 5.04602761 4.25491852 0.55028749 0.80248744]
 [3.82442764 6.00603363 4.12323129 0.56333505 0.7444752 ]
 [3.98323181 7.00528516 4.11573651 0.589533   0.71309711]
 [4.05008771 7.96529118 3.98404928 0.60258057 0.65508487]
 [4.1135437  9.00923788 3.82741928 0.61546144 0.58899422]]
--------------------------------------------------
A_tilde rank = 
 2
--------------------------------------------------
error = 
 2.2465272268175456


In [20]:
#type your code here:


---------------------------------------------
k =
 2
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
---------------------------------------------
A_tilde = 
 [[0.97120303 0.97817264 1.17745474 0.14101019 0.2345008 ]
 [3.66822055 3.92867295 4.39143298 0.53346975 0.86625708]
 [3.59876756 4.04677607 4.2624133  0.52408954 0.83386553]
 [3.75757173 5.04602761 4.25491852 0.55028749 0.80248744]
 [3.82442764 6.00603363 4.12323129 0.56333505 0.7444752 ]
 [3.98323181 7.00528516 4.11573651 0.589533   0.71309711]
 [4.05008771 7.96529118 3.98404928 0.60258057 0.65508487]
 [4.1135437  9.00923788 3.82741928 0.61546144 0.58899422]]
---------------------------------------------
A_tilde_rank = 
 2
---------------------------------------------
error = 
 2.2465272268175456


In [49]:
print("-"*50)
k=1
print("k = \n",k)

print("-"*50)
print("A =\n",A)

print("-"*50)
A_tilde=U[:,:k] @ S[:k,:k] @ VT[:k,:]
print("A_tilde =\n",A_tilde)

print("-"*50)
print("A_tilde rank = \n",np.linalg.matrix_rank(A_tilde))

print("-"*50)
print("error = \n",np.linalg.norm(A-A_tilde))

--------------------------------------------------
k = 
 1
--------------------------------------------------
A =
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
--------------------------------------------------
A_tilde =
 [[0.79493186 1.31209448 0.84185871 0.1173312  0.14945219]
 [3.06849251 5.06477638 3.24963343 0.45290665 0.57689591]
 [3.06469381 5.05850635 3.24561049 0.45234596 0.57618173]
 [3.43143763 5.66384444 3.63400412 0.50647701 0.64513187]
 [3.73797475 6.16980689 3.95863691 0.5517216  0.70276278]
 [4.10471857 6.77514498 4.34703055 0.60585265 0.77171293]
 [4.41125569 7.28110744 4.67166334 0.65109724 0.82934383]
 [4.73965497 7.823155   5.01944886 0.69956867 0.89108496]]
--------------------------------------------------
A_tilde rank = 
 1
--------------------------------------------------
error = 
 4.034736338985961


In [21]:
#type your code here:


---------------------------------------------
k =
 1
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
---------------------------------------------
A_tilde = 
 [[0.79493186 1.31209448 0.84185871 0.1173312  0.14945219]
 [3.06849251 5.06477638 3.24963343 0.45290665 0.57689591]
 [3.06469381 5.05850635 3.24561049 0.45234596 0.57618173]
 [3.43143763 5.66384444 3.63400412 0.50647701 0.64513187]
 [3.73797475 6.16980689 3.95863691 0.5517216  0.70276278]
 [4.10471857 6.77514498 4.34703055 0.60585265 0.77171293]
 [4.41125569 7.28110744 4.67166334 0.65109724 0.82934383]
 [4.73965497 7.823155   5.01944886 0.69956867 0.89108496]]
---------------------------------------------
A_tilde_rank = 
 1
---------------------------------------------
error = 
 4.034736338985961
